name: stacktower
description: Stack Tower

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #three_dart:
  #  git:
  #    url: 'https://github.com/Knightro63/three_dart.git'
  #three_dart_jsm:
  #  git:
  #    url: 'https://github.com/Knightro63/three_dart_jsm.git'
  #openworld:
  #  git:
      #    #url: 'https://github.com/wasabia/flutter_gl'
  #   url: 'https://github.com/forthtemple/openworlddart.git'
  #openworld_gl:
  #  git:
  #    #url: 'https://github.com/wasabia/flutter_gl'
  #    url: 'https://github.com/forthtemple/openworld_gl.git'
  #    path: ./flutter_gl
  # universal_ui: ^0.0.8
  #flutter_gl: ^0.0.21
  #oimo_physics: ^0.0.1
  #flutter_joystick: ^0.0.3
  #flutter_joystick: ^0.2.0
  #flutter_soloud: ^2.0.2
  #path_provider_windows: ^2.2.1
  #just_audio: ^0.9.38
  #audioplayers: ^6.0.0
  audioplayers: ^6.1.0
  #vector_math: ^2.1.4
  #confirm_dialog: ^1.0.3
  #prompt_dialog: ^1.0.16
  #xml2json: ^6.2.3
  #event: ^2.1.2
  shared_preferences: ^2.2.3
  widget_zoom: ^0.0.4
  font_awesome_flutter: ^10.7.0
  #widget_and_text_animator: ^1.1.5
  #fluttertoast: ^8.2.6
  #flutter_user_guildance: ^2.0.7
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  win32: ^5.5.4
  archive: ^3.6.1
  window_manager: ^0.4.3
  #desktop_window: ^0.4.2

  openworld: ^0.0.9
  openworld_gl: ^0.0.25
  #openworld:
  #  path: ../
  #openworld_gl:
  #  path: ../../openworld_gl/openworld_gl

dependency_overrides:
  #openworld:
  #  path: ../
  #openworld_gl:
  #  path: ../../openworld_gl

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  assets:
    # - assets/helvetiker_bold.typeface.json

    - icons/
    - assets/textures/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "ic_launcher"
  image_path: "icons/stacktower.png"
  ios: true
  windows:
    generate: true
    image_path: "icons/stacktower.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "icons/stacktower.png"
    icon_size: 48