name: stacktower # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Stack a tower high # 79 char long summary
description: |
  Make a tower as tall as you can. Press 'Start' to begin and then press space to send the block down to the foundation stone.
icon: snap/gui/stacktower.png
website: https://github.com/forthtemple/stacktower/tree/main/
source-code: https://github.com/forthtemple/stacktower/tree/main/

grade: stable #devel # must be '' to release into candidate/stable channels
confinement: strict #devmode # use 'strict' once you have the right plugs and slots

apps:
  stacktower:
    command: stacktower
    extensions: [gnome]
    plugs:
      - opengl 

parts:
  stacktower:
    source: .
    #source: ../../openworlddart/examplesecondtemple/
    source-type: local
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libglew-dev
      #- libglew-2.2
      #- libblas-dev 
      #- liblapack-dev
      - libatlas-base-dev
    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libglew2.2
      - libatlas3-base
      #- liblapack3
      #- libblas3
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
      usr/lib/*-linux-gnu/atlas/*: usr/lib/
 
